version: "3"
services:
  php:
    container_name: "php"
    build:
      context: .
      args:
        host: $HOST
    command: php -S 0.0.0.0:80 -t /app
    ports:
      - "80:80"
    volumes:
      - .:/app

  composer:
    image: composer:latest
    volumes:
      - .:/app
    links:
      - php